version: "3"

vars:
  HOST:
    sh: "hostname"
  NIXPKGS_ALLOW_UNFREE: 1

env:
  NIXPKGS_ALLOW_UNFREE: 1

dotenv: [".env"]

tasks:
  apply:
    desc: "Nix Darwin の設定をビルドして適用します"
    platforms: [darwin]
    cmds:
      - |
        nix build .#darwinConfigurations.{{.HOST}}.system --extra-experimental-features 'nix-command flakes'
        sudo ./result/sw/bin/darwin-rebuild switch --flake ".#{{.HOST}}"

  eval:
    desc: "Nix evaluation の時間を計測します"
    platforms: [darwin]
    cmds:
      - |
        time nix eval .#darwinConfigurations.{{.HOST}}.system --apply 'x: "ok"' --extra-experimental-features 'nix-command flakes'

  dry-run:
    desc: "ビルド対象のパッケージを確認します（実際にはビルドしない）"
    platforms: [darwin]
    cmds:
      - nix build .#darwinConfigurations.{{.HOST}}.system --extra-experimental-features 'nix-command flakes' --dry-run

  diff:
    desc: "現在のシステムプロファイルとの差分を表示します"
    platforms: [darwin]
    cmds:
      - |
        nix build .#darwinConfigurations.{{.HOST}}.system --extra-experimental-features 'nix-command flakes'
        nix store diff-closures /nix/var/nix/profiles/system ./result

  gc:
    desc: "Nix ストアのガベージコレクションを実行します"
    cmds:
      - nix-collect-garbage --delete-older-than 30d

  gc-all:
    desc: "すべての古い世代を削除します（現在の世代のみ保持）"
    cmds:
      - nix-collect-garbage -d

  upgrade-nix:
    desc: "determinate nix をアップグレードします"
    cmds:
      - sudo determinate-nixd upgrade

  update:
    desc: "flake の入力を更新します"
    cmds:
      - nix flake update

  update-nixpkgs:
    desc: "nixpkgs のみを更新します"
    cmds:
      - nix flake update nixpkgs
